// ============================================================================
// FILE: src/data/shopDummyData.ts
// Dummy data for Shop module - 15 shops with realistic Indian jewelry shop data
// ============================================================================

import {
  Shop,
  ShopType,
  ShopCategory,
  ShopStatus,
  ShopCurrency,
  ShopLanguage,
  WeightUnit,
} from '@/types'

// ============================================================================
// DUMMY SHOPS DATA
// ============================================================================

export const dummyShops: Shop[] = [
  {
    _id: '6501a1b2c3d4e5f6a7b8c9d0',
    code: 'SRI-GJ-001',
    name: 'Shri Krishna Jewellers',
    displayName: 'SK Jewellers',
    organizationId: {
      _id: '6401a1b2c3d4e5f6a7b8c9d0',
      name: 'Krishna Jewelry Group',
      displayName: 'KJG',
      email: 'info@kjgroup.com',
      phone: '9876543210',
    },
    managerId: {
      _id: '6301a1b2c3d4e5f6a7b8c9d0',
      firstName: 'Rajesh',
      lastName: 'Patel',
      email: 'rajesh.patel@kjgroup.com',
      phone: '9876543210',
    },
    email: 'info@skkjewellers.com',
    phone: '9876543210',
    alternatePhone: '9876543211',
    whatsappNumber: '9876543210',
    website: 'www.skkjewellers.com',
    address: {
      street: '123, MG Road, Near City Mall',
      city: 'Ahmedabad',
      state: 'Gujarat',
      country: 'India',
      pincode: '380001',
      landmark: 'Opposite HDFC Bank',
      location: {
        type: 'Point',
        coordinates: [72.5714, 23.0225],
      },
    },
    gstNumber: '24AAACP1234A1Z5',
    panNumber: 'AAACP1234A',
    shopType: ShopType.RETAIL,
    category: ShopCategory.MIXED,
    status: ShopStatus.ACTIVE,
    establishedYear: 1985,
    openingDate: '1985-05-15',
    bankDetails: [
      {
        _id: '6601a1b2c3d4e5f6a7b8c9d0',
        bankName: 'HDFC Bank',
        accountNumber: '50100123456789',
        ifscCode: 'HDFC0001234',
        accountHolderName: 'Shri Krishna Jewellers',
        branchName: 'MG Road Branch',
        accountType: 'current',
        isActive: true,
        isPrimary: true,
      },
    ],
    upiDetails: [
      {
        _id: '6701a1b2c3d4e5f6a7b8c9d0',
        upiId: 'skkjewellers@hdfcbank',
        name: 'SK Jewellers',
        isActive: true,
        isPrimary: true,
      },
    ],
    settings: {
      currency: ShopCurrency.INR,
      language: ShopLanguage.GU,
      defaultWeightUnit: WeightUnit.GRAM,
      enableGST: true,
      gstRates: {
        gold: 3,
        silver: 3,
        diamond: 0.25,
        making: 5,
      },
      metalRates: {
        gold: {
          rate24K: 6450,
          rate22K: 5915,
          rate18K: 4840,
        },
        silver: {
          rate999: 78,
          rate925: 72,
        },
        lastUpdated: '2024-12-15T10:30:00Z',
      },
    },
    features: {
      enableInventory: true,
      enablePOS: true,
      enableECommerce: true,
      enableRepairs: true,
      enableCustomOrders: true,
      enableSchemes: true,
      enableLoyalty: true,
    },
    statistics: {
      totalProducts: 1250,
      totalInventoryValue: 15500000,
      totalSales: 3200,
      totalSalesAmount: 45000000,
      totalCustomers: 2800,
      totalOrders: 3500,
      averageOrderValue: 14062,
      lowStockItems: 15,
      lastUpdated: '2024-12-15T10:00:00Z',
    },
    isActive: true,
    isVerified: true,
    isFeatured: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-12-15T10:00:00Z',
  },

  {
    _id: '6502a1b2c3d4e5f6a7b8c9d1',
    code: 'TAN-MH-002',
    name: 'Tanishq - Phoenix Mall',
    displayName: 'Tanishq Phoenix',
    organizationId: {
      _id: '6402a1b2c3d4e5f6a7b8c9d1',
      name: 'Titan Company Limited',
      displayName: 'Titan',
    },
    managerId: {
      _id: '6302a1b2c3d4e5f6a7b8c9d1',
      firstName: 'Priya',
      lastName: 'Sharma',
      email: 'priya.sharma@tanishq.co.in',
      phone: '9823456789',
    },
    email: 'phoenix@tanishq.co.in',
    phone: '9823456789',
    whatsappNumber: '9823456789',
    website: 'www.tanishq.co.in',
    address: {
      street: 'Phoenix Marketcity, LBS Marg',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400070',
      landmark: 'Kurla West',
      location: {
        type: 'Point',
        coordinates: [72.8777, 19.076],
      },
    },
    gstNumber: '27AAACP5678B1Z2',
    panNumber: 'AAACP5678B',
    shopType: ShopType.SHOWROOM,
    category: ShopCategory.JEWELRY,
    status: ShopStatus.ACTIVE,
    establishedYear: 2010,
    openingDate: '2010-08-20',
    bankDetails: [
      {
        bankName: 'State Bank of India',
        accountNumber: '12345678901234',
        ifscCode: 'SBIN0005678',
        accountHolderName: 'Tanishq - Phoenix Mall',
        accountType: 'current',
        isActive: true,
        isPrimary: true,
      },
    ],
    upiDetails: [
      {
        upiId: 'tanishq.phoenix@sbi',
        name: 'Tanishq Phoenix',
        isActive: true,
        isPrimary: true,
      },
    ],
    settings: {
      currency: ShopCurrency.INR,
      language: ShopLanguage.HI,
      defaultWeightUnit: WeightUnit.GRAM,
      enableGST: true,
      gstRates: {
        gold: 3,
        silver: 3,
        diamond: 0.25,
        making: 5,
      },
      metalRates: {
        gold: {
          rate24K: 6475,
          rate22K: 5935,
          rate18K: 4855,
        },
        silver: {
          rate999: 79,
          rate925: 73,
        },
        lastUpdated: '2024-12-15T09:00:00Z',
      },
    },
    features: {
      enableInventory: true,
      enablePOS: true,
      enableECommerce: true,
      enableRepairs: true,
      enableCustomOrders: true,
      enableSchemes: true,
      enableLoyalty: true,
    },
    statistics: {
      totalProducts: 2500,
      totalInventoryValue: 35000000,
      totalSales: 5600,
      totalSalesAmount: 85000000,
      totalCustomers: 4200,
      totalOrders: 6100,
      averageOrderValue: 13934,
      lowStockItems: 8,
      lastUpdated: '2024-12-15T09:00:00Z',
    },
    isActive: true,
    isVerified: true,
    isFeatured: true,
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2024-12-15T09:00:00Z',
  },

  {
    _id: '6503a1b2c3d4e5f6a7b8c9d2',
    code: 'CHE-TN-003',
    name: 'Chennai Silks Jewelry',
    displayName: 'CS Jewelry',
    organizationId: {
      _id: '6403a1b2c3d4e5f6a7b8c9d2',
      name: 'Chennai Silks Group',
      displayName: 'CS Group',
    },
    managerId: {
      _id: '6303a1b2c3d4e5f6a7b8c9d2',
      firstName: 'Sundar',
      lastName: 'Raman',
      email: 'sundar@chennaisilks.com',
      phone: '9445123456',
    },
    email: 'jewelry@chennaisilks.com',
    phone: '9445123456',
    alternatePhone: '9445123457',
    whatsappNumber: '9445123456',
    website: 'www.chennaisilksjewelry.com',
    address: {
      street: '45, T. Nagar Main Road',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      pincode: '600017',
      landmark: 'Near Pondy Bazaar',
      location: {
        type: 'Point',
        coordinates: [80.2707, 13.0827],
      },
    },
    gstNumber: '33BBBCP9012C1Z8',
    panNumber: 'BBBCP9012C',
    shopType: ShopType.RETAIL,
    category: ShopCategory.GOLD,
    status: ShopStatus.ACTIVE,
    establishedYear: 1975,
    openingDate: '1975-03-10',
    bankDetails: [
      {
        bankName: 'Indian Bank',
        accountNumber: '98765432109876',
        ifscCode: 'IDIB0009876',
        accountHolderName: 'Chennai Silks Jewelry',
        accountType: 'current',
        isActive: true,
        isPrimary: true,
      },
    ],
    upiDetails: [
      {
        upiId: 'chennaisilks@indianbank',
        name: 'CS Jewelry',
        isActive: true,
        isPrimary: true,
      },
    ],
    settings: {
      currency: ShopCurrency.INR,
      language: ShopLanguage.TA,
      defaultWeightUnit: WeightUnit.GRAM,
      enableGST: true,
      gstRates: {
        gold: 3,
        silver: 3,
        making: 5,
      },
      metalRates: {
        gold: {
          rate24K: 6460,
          rate22K: 5925,
          rate18K: 4845,
        },
        silver: {
          rate999: 78.5,
          rate925: 72.5,
        },
        lastUpdated: '2024-12-15T08:30:00Z',
      },
    },
    features: {
      enableInventory: true,
      enablePOS: true,
      enableECommerce: false,
      enableRepairs: true,
      enableCustomOrders: true,
      enableSchemes: true,
      enableLoyalty: true,
    },
    statistics: {
      totalProducts: 1800,
      totalInventoryValue: 25000000,
      totalSales: 4200,
      totalSalesAmount: 62000000,
      totalCustomers: 3500,
      totalOrders: 4500,
      averageOrderValue: 13777,
      lowStockItems: 12,
      lastUpdated: '2024-12-15T08:30:00Z',
    },
    isActive: true,
    isVerified: true,
    isFeatured: true,
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-12-15T08:30:00Z',
  },

  {
    _id: '6504a1b2c3d4e5f6a7b8c9d3',
    code: 'MEL-KA-004',
    name: 'Malabar Gold - Jayanagar',
    displayName: 'Malabar Jayanagar',
    organizationId: {
      _id: '6404a1b2c3d4e5f6a7b8c9d3',
      name: 'Malabar Gold & Diamonds',
      displayName: 'Malabar',
    },
    managerId: {
      _id: '6304a1b2c3d4e5f6a7b8c9d3',
      firstName: 'Anil',
      lastName: 'Kumar',
      email: 'anil.kumar@malabargold.in',
      phone: '9876012345',
    },
    email: 'jayanagar@malabargold.in',
    phone: '9876012345',
    whatsappNumber: '9876012345',
    website: 'www.malabargoldanddiamonds.com',
    address: {
      street: '234, 4th Block, Jayanagar',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
      pincode: '560041',
      landmark: 'Near Jayanagar Shopping Complex',
      location: {
        type: 'Point',
        coordinates: [77.5946, 12.9716],
      },
    },
    gstNumber: '29CCCCP3456D1Z4',
    panNumber: 'CCCCP3456D',
    shopType: ShopType.SHOWROOM,
    category: ShopCategory.MIXED,
    status: ShopStatus.ACTIVE,
    establishedYear: 2015,
    openingDate: '2015-06-12',
    bankDetails: [
      {
        bankName: 'Federal Bank',
        accountNumber: '15234567890123',
        ifscCode: 'FDRL0001523',
        accountHolderName: 'Malabar Gold - Jayanagar',
        accountType: 'current',
        isActive: true,
        isPrimary: true,
      },
    ],
    upiDetails: [
      {
        upiId: 'malabar.jayanagar@federal',
        name: 'Malabar Jayanagar',
        isActive: true,
        isPrimary: true,
      },
    ],
    settings: {
      currency: ShopCurrency.INR,
      language: ShopLanguage.EN,
      defaultWeightUnit: WeightUnit.GRAM,
      enableGST: true,
      gstRates: {
        gold: 3,
        silver: 3,
        diamond: 0.25,
        making: 5,
      },
      metalRates: {
        gold: {
          rate24K: 6480,
          rate22K: 5940,
          rate18K: 4860,
        },
        silver: {
          rate999: 79.5,
          rate925: 73.5,
        },
        platinum: {
          rate: 3250,
        },
        lastUpdated: '2024-12-15T10:15:00Z',
      },
    },
    features: {
      enableInventory: true,
      enablePOS: true,
      enableECommerce: true,
      enableRepairs: true,
      enableCustomOrders: true,
      enableSchemes: true,
      enableLoyalty: true,
    },
    statistics: {
      totalProducts: 3200,
      totalInventoryValue: 48000000,
      totalSales: 6800,
      totalSalesAmount: 95000000,
      totalCustomers: 5200,
      totalOrders: 7200,
      averageOrderValue: 13194,
      lowStockItems: 20,
      lastUpdated: '2024-12-15T10:15:00Z',
    },
    isActive: true,
    isVerified: true,
    isFeatured: true,
    createdAt: '2024-03-05T08:00:00Z',
    updatedAt: '2024-12-15T10:15:00Z',
  },

  {
    _id: '6505a1b2c3d4e5f6a7b8c9d4',
    code: 'JOY-DL-005',
    name: 'Joyalukkas - Karol Bagh',
    displayName: 'Joyalukkas KB',
    organizationId: {
      _id: '6405a1b2c3d4e5f6a7b8c9d4',
      name: 'Joyalukkas India Pvt Ltd',
      displayName: 'Joyalukkas',
    },
    managerId: {
      _id: '6305a1b2c3d4e5f6a7b8c9d4',
      firstName: 'Vikram',
      lastName: 'Singh',
      email: 'vikram.singh@joyalukkas.com',
      phone: '9810234567',
    },
    email: 'karolbagh@joyalukkas.com',
    phone: '9810234567',
    whatsappNumber: '9810234567',
    website: 'www.joyalukkas.in',
    address: {
      street: '567, Ajmal Khan Road',
      city: 'New Delhi',
      state: 'Delhi',
      country: 'India',
      pincode: '110005',
      landmark: 'Near Metro Station',
      location: {
        type: 'Point',
        coordinates: [77.209, 28.7041],
      },
    },
    gstNumber: '07DDDCP7890E1Z6',
    panNumber: 'DDDCP7890E',
    shopType: ShopType.SHOWROOM,
    category: ShopCategory.JEWELRY,
    status: ShopStatus.ACTIVE,
    establishedYear: 2012,
    openingDate: '2012-11-05',
    bankDetails: [
      {
        bankName: 'ICICI Bank',
        accountNumber: '00456789012345',
        ifscCode: 'ICIC0000045',
        accountHolderName: 'Joyalukkas - Karol Bagh',
        accountType: 'current',
        isActive: true,
        isPrimary: true,
      },
    ],
    upiDetails: [
      {
        upiId: 'joyalukkas.kb@icici',
        name: 'Joyalukkas KB',
        isActive: true,
        isPrimary: true,
      },
    ],
    settings: {
      currency: ShopCurrency.INR,
      language: ShopLanguage.HI,
      defaultWeightUnit: WeightUnit.GRAM,
      enableGST: true,
      gstRates: {
        gold: 3,
        silver: 3,
        diamond: 0.25,
        making: 5,
      },
      metalRates: {
        gold: {
          rate24K: 6470,
          rate22K: 5930,
          rate18K: 4850,
        },
        silver: {
          rate999: 79,
          rate925: 73,
        },
        platinum: {
          rate: 3240,
        },
        lastUpdated: '2024-12-15T09:45:00Z',
      },
    },
    features: {
      enableInventory: true,
      enablePOS: true,
      enableECommerce: true,
      enableRepairs: true,
      enableCustomOrders: true,
      enableSchemes: false,
      enableLoyalty: true,
    },
    statistics: {
      totalProducts: 2800,
      totalInventoryValue: 42000000,
      totalSales: 5400,
      totalSalesAmount: 78000000,
      totalCustomers: 4800,
      totalOrders: 5800,
      averageOrderValue: 13448,
      lowStockItems: 18,
      lastUpdated: '2024-12-15T09:45:00Z',
    },
    isActive: true,
    isVerified: true,
    isFeatured: false,
    createdAt: '2024-02-28T08:00:00Z',
    updatedAt: '2024-12-15T09:45:00Z',
  },

  {
    _id: '6506a1b2c3d4e5f6a7b8c9d5',
    code: 'KAL-RJ-006',
    name: 'Kalyan Jewellers - Jaipur',
    displayName: 'Kalyan Jaipur',
    organizationId: {
      _id: '6406a1b2c3d4e5f6a7b8c9d5',
      name: 'Kalyan Jewellers India Ltd',
      displayName: 'Kalyan',
    },
    managerId: {
      _id: '6306a1b2c3d4e5f6a7b8c9d5',
      firstName: 'Mohan',
      lastName: 'Rajput',
      email: 'mohan.rajput@kalyanjewellers.net',
      phone: '9414567890',
    },
    email: 'jaipur@kalyanjewellers.net',
    phone: '9414567890',
    whatsappNumber: '9414567890',
    website: 'www.kalyanjewellers.net',
    address: {
      street: '89, MI Road, Near Panch Batti',
      city: 'Jaipur',
      state: 'Rajasthan',
      country: 'India',
      pincode: '302001',
      landmark: 'Opposite City Palace',
      location: {
        type: 'Point',
        coordinates: [75.7873, 26.9124],
      },
    },
    gstNumber: '08EEECP1122F1Z9',
    panNumber: 'EEECP1122F',
    shopType: ShopType.SHOWROOM,
    category: ShopCategory.JEWELRY,
    status: ShopStatus.ACTIVE,
    establishedYear: 2014,
    openingDate: '2014-09-18',
    bankDetails: [
      {
        bankName: 'Axis Bank',
        accountNumber: '91234567890123',
        ifscCode: 'UTIB0009123',
        accountHolderName: 'Kalyan Jewellers - Jaipur',
        accountType: 'current',
        isActive: true,
        isPrimary: true,
      },
    ],
    upiDetails: [
      {
        upiId: 'kalyan.jaipur@axisbank',
        name: 'Kalyan Jaipur',
        isActive: true,
        isPrimary: true,
      },
    ],
    settings: {
      currency: ShopCurrency.INR,
      language: ShopLanguage.HI,
      defaultWeightUnit: WeightUnit.GRAM,
      enableGST: true,
      gstRates: {
        gold: 3,
        silver: 3,
        diamond: 0.25,
        making: 5,
      },
      metalRates: {
        gold: {
          rate24K: 6455,
          rate22K: 5920,
          rate18K: 4842,
        },
        silver: {
          rate999: 78,
          rate925: 72,
        },
        lastUpdated: '2024-12-15T09:00:00Z',
      },
    },
    features: {
      enableInventory: true,
      enablePOS: true,
      enableECommerce: true,
      enableRepairs: true,
      enableCustomOrders: true,
      enableSchemes: true,
      enableLoyalty: true,
    },
    statistics: {
      totalProducts: 2200,
      totalInventoryValue: 32000000,
      totalSales: 4600,
      totalSalesAmount: 68000000,
      totalCustomers: 3900,
      totalOrders: 5000,
      averageOrderValue: 13600,
      lowStockItems: 14,
      lastUpdated: '2024-12-15T09:00:00Z',
    },
    isActive: true,
    isVerified: true,
    isFeatured: true,
    createdAt: '2024-03-12T08:00:00Z',
    updatedAt: '2024-12-15T09:00:00Z',
  },

  {
    _id: '6507a1b2c3d4e5f6a7b8c9d6',
    code: 'BHA-WB-007',
    name: 'Bhima Jewellers - Kolkata',
    displayName: 'Bhima Kolkata',
    organizationId: {
      _id: '6407a1b2c3d4e5f6a7b8c9d6',
      name: 'Bhima Jewellers Pvt Ltd',
      displayName: 'Bhima',
    },
    managerId: {
      _id: '6307a1b2c3d4e5f6a7b8c9d6',
      firstName: 'Suresh',
      lastName: 'Chatterjee',
      email: 'suresh.c@bhimajewellers.com',
      phone: '9830123456',
    },
    email: 'kolkata@bhimajewellers.com',
    phone: '9830123456',
    whatsappNumber: '9830123456',
    website: 'www.bhimajewellers.com',
    address: {
      street: '145, Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
      pincode: '700016',
      landmark: 'Near Park Street Metro',
      location: {
        type: 'Point',
        coordinates: [88.3639, 22.5726],
      },
    },
    gstNumber: '19FFFCP4455G1Z3',
    panNumber: 'FFFCP4455G',
    shopType: ShopType.RETAIL,
    category: ShopCategory.GOLD,
    status: ShopStatus.ACTIVE,
    establishedYear: 1980,
    openingDate: '1980-07-22',
    bankDetails: [
      {
        bankName: 'Punjab National Bank',
        accountNumber: '65432109876543',
        ifscCode: 'PUNB0065432',
        accountHolderName: 'Bhima Jewellers - Kolkata',
        accountType: 'current',
        isActive: true,
        isPrimary: true,
      },
    ],
    upiDetails: [
      {
        upiId: 'bhima.kolkata@pnb',
        name: 'Bhima Kolkata',
        isActive: true,
        isPrimary: true,
      },
    ],
    settings: {
      currency: ShopCurrency.INR,
      language: ShopLanguage.EN,
      defaultWeightUnit: WeightUnit.GRAM,
      enableGST: true,
      gstRates: {
        gold: 3,
        silver: 3,
        making: 5,
      },
      metalRates: {
        gold: {
          rate24K: 6465,
          rate22K: 5927,
          rate18K: 4848,
        },
        silver: {
          rate999: 78.8,
          rate925: 72.8,
        },
        lastUpdated: '2024-12-15T08:45:00Z',
      },
    },
    features: {
      enableInventory: true,
      enablePOS: true,
      enableECommerce: false,
      enableRepairs: true,
      enableCustomOrders: true,
      enableSchemes: true,
      enableLoyalty: false,
    },
    statistics: {
      totalProducts: 1500,
      totalInventoryValue: 22000000,
      totalSales: 3800,
      totalSalesAmount: 55000000,
      totalCustomers: 3200,
      totalOrders: 4100,
      averageOrderValue: 13414,
      lowStockItems: 10,
      lastUpdated: '2024-12-15T08:45:00Z',
    },
    isActive: true,
    isVerified: true,
    isFeatured: false,
    createdAt: '2024-01-25T08:00:00Z',
    updatedAt: '2024-12-15T08:45:00Z',
  },
]
