// ============================================================================
// FILE: src/components/features/CustomerTable/CustomerTable.types.ts
// Customer Table TypeScript Types & Mock Data
// ============================================================================

export interface Customer {
  _id: string
  customerCode: string
  firstName: string
  lastName: string
  fullName: string
  phone: string
  email: string
  customerType: 'retail' | 'wholesale' | 'vip' | 'regular'
  membershipTier: 'standard' | 'silver' | 'gold' | 'platinum'
  totalPurchases: number
  totalDue: number
  loyaltyPoints: number
  isActive: boolean
  isBlacklisted: boolean
  createdAt: string
}

// ============================================================================
// MOCK DATA
// ============================================================================

export const MOCK_CUSTOMERS: Customer[] = [
  {
    _id: '1',
    customerCode: 'CUST00001',
    firstName: 'Rajesh',
    lastName: 'Kumar',
    fullName: 'Rajesh Kumar',
    phone: '9876543210',
    email: 'rajesh.kumar@example.com',
    customerType: 'vip',
    membershipTier: 'platinum',
    totalPurchases: 450000,
    totalDue: 25000,
    loyaltyPoints: 1250,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    _id: '2',
    customerCode: 'CUST00002',
    firstName: 'Priya',
    lastName: 'Sharma',
    fullName: 'Priya Sharma',
    phone: '9123456789',
    email: 'priya.sharma@example.com',
    customerType: 'retail',
    membershipTier: 'gold',
    totalPurchases: 180000,
    totalDue: 0,
    loyaltyPoints: 890,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2024-02-20T14:15:00Z',
  },
  {
    _id: '3',
    customerCode: 'CUST00003',
    firstName: 'Amit',
    lastName: 'Patel',
    fullName: 'Amit Patel',
    phone: '9988776655',
    email: 'amit.patel@example.com',
    customerType: 'wholesale',
    membershipTier: 'silver',
    totalPurchases: 320000,
    totalDue: 15000,
    loyaltyPoints: 650,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    _id: '4',
    customerCode: 'CUST00004',
    firstName: 'Sneha',
    lastName: 'Reddy',
    fullName: 'Sneha Reddy',
    phone: '9876512345',
    email: 'sneha.reddy@example.com',
    customerType: 'retail',
    membershipTier: 'standard',
    totalPurchases: 95000,
    totalDue: 5000,
    loyaltyPoints: 320,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2024-03-05T11:45:00Z',
  },
  {
    _id: '5',
    customerCode: 'CUST00005',
    firstName: 'Vikas',
    lastName: 'Singh',
    fullName: 'Vikas Singh',
    phone: '9765432108',
    email: 'vikas.singh@example.com',
    customerType: 'vip',
    membershipTier: 'platinum',
    totalPurchases: 580000,
    totalDue: 0,
    loyaltyPoints: 1850,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2023-11-22T08:30:00Z',
  },
  {
    _id: '6',
    customerCode: 'CUST00006',
    firstName: 'Kavita',
    lastName: 'Gupta',
    fullName: 'Kavita Gupta',
    phone: '9812345678',
    email: 'kavita.gupta@example.com',
    customerType: 'regular',
    membershipTier: 'standard',
    totalPurchases: 45000,
    totalDue: 2500,
    loyaltyPoints: 150,
    isActive: false,
    isBlacklisted: false,
    createdAt: '2024-04-12T16:20:00Z',
  },
  {
    _id: '7',
    customerCode: 'CUST00007',
    firstName: 'Rahul',
    lastName: 'Mehta',
    fullName: 'Rahul Mehta',
    phone: '9923456789',
    email: 'rahul.mehta@example.com',
    customerType: 'wholesale',
    membershipTier: 'gold',
    totalPurchases: 275000,
    totalDue: 35000,
    loyaltyPoints: 720,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2024-02-08T13:10:00Z',
  },
  {
    _id: '8',
    customerCode: 'CUST00008',
    firstName: 'Deepa',
    lastName: 'Joshi',
    fullName: 'Deepa Joshi',
    phone: '9834567890',
    email: 'deepa.joshi@example.com',
    customerType: 'retail',
    membershipTier: 'silver',
    totalPurchases: 125000,
    totalDue: 8000,
    loyaltyPoints: 480,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2024-03-18T10:05:00Z',
  },
  {
    _id: '9',
    customerCode: 'CUST00009',
    firstName: 'Suresh',
    lastName: 'Rao',
    fullName: 'Suresh Rao',
    phone: '9745678901',
    email: 'suresh.rao@example.com',
    customerType: 'vip',
    membershipTier: 'gold',
    totalPurchases: 390000,
    totalDue: 0,
    loyaltyPoints: 1120,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2023-12-15T09:30:00Z',
  },
  {
    _id: '10',
    customerCode: 'CUST00010',
    firstName: 'Anjali',
    lastName: 'Verma',
    fullName: 'Anjali Verma',
    phone: '9656789012',
    email: 'anjali.verma@example.com',
    customerType: 'regular',
    membershipTier: 'standard',
    totalPurchases: 62000,
    totalDue: 12000,
    loyaltyPoints: 210,
    isActive: true,
    isBlacklisted: true,
    createdAt: '2024-01-28T15:40:00Z',
  },
  {
    _id: '11',
    customerCode: 'CUST00011',
    firstName: 'Manish',
    lastName: 'Agarwal',
    fullName: 'Manish Agarwal',
    phone: '9567890123',
    email: 'manish.agarwal@example.com',
    customerType: 'wholesale',
    membershipTier: 'platinum',
    totalPurchases: 520000,
    totalDue: 28000,
    loyaltyPoints: 1420,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2023-10-05T11:15:00Z',
  },
  {
    _id: '12',
    customerCode: 'CUST00012',
    firstName: 'Pooja',
    lastName: 'Nair',
    fullName: 'Pooja Nair',
    phone: '9478901234',
    email: 'pooja.nair@example.com',
    customerType: 'retail',
    membershipTier: 'gold',
    totalPurchases: 210000,
    totalDue: 0,
    loyaltyPoints: 950,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2024-02-14T12:50:00Z',
  },
  {
    _id: '13',
    customerCode: 'CUST00013',
    firstName: 'Karan',
    lastName: 'Malhotra',
    fullName: 'Karan Malhotra',
    phone: '9389012345',
    email: 'karan.malhotra@example.com',
    customerType: 'vip',
    membershipTier: 'platinum',
    totalPurchases: 680000,
    totalDue: 15000,
    loyaltyPoints: 2100,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2023-09-20T08:00:00Z',
  },
  {
    _id: '14',
    customerCode: 'CUST00014',
    firstName: 'Neha',
    lastName: 'Chopra',
    fullName: 'Neha Chopra',
    phone: '9290123456',
    email: 'neha.chopra@example.com',
    customerType: 'regular',
    membershipTier: 'silver',
    totalPurchases: 78000,
    totalDue: 4500,
    loyaltyPoints: 280,
    isActive: true,
    isBlacklisted: false,
    createdAt: '2024-03-25T14:30:00Z',
  },
  {
    _id: '15',
    customerCode: 'CUST00015',
    firstName: 'Sanjay',
    lastName: 'Desai',
    fullName: 'Sanjay Desai',
    phone: '9101234567',
    email: 'sanjay.desai@example.com',
    customerType: 'wholesale',
    membershipTier: 'gold',
    totalPurchases: 340000,
    totalDue: 22000,
    loyaltyPoints: 890,
    isActive: false,
    isBlacklisted: false,
    createdAt: '2024-01-30T10:20:00Z',
  },
]