// SUPPLIER MODULE - COMPREHENSIVE DUMMY DATA

import {
  Supplier,
  SupplierType,
  SupplierCategory,
  PaymentTerms,
  CertificationType,
  DocumentType,
  AccountType,
} from '@/types/supplier.types'

// SINGLE SUPPLIERS (Individual detailed data)

export const dummySupplier: Supplier = {
  _id: '6745a8b3c9d2e1f4a5b6c7d8',
  organizationId: 'org_123456789',
  shopId: 'shop_987654321',
  supplierCode: 'SUP00001',

  businessName: 'Rajesh Gold Suppliers Pvt Ltd',
  displayName: 'Rajesh Gold',

  contactPerson: {
    firstName: 'Rajesh',
    lastName: 'Kumar',
    designation: 'Managing Director',
    email: 'rajesh@rajeshgold.com',
    phone: '9876543210',
    alternatePhone: '9876543211',
    whatsappNumber: '9876543210',
  },

  businessEmail: 'info@rajeshgold.com',
  businessPhone: '02212345678',
  website: 'https://www.rajeshgold.com',

  address: {
    street: '123, Zaveri Bazaar',
    landmark: 'Near Jain Temple',
    area: 'Kalbadevi',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    pincode: '400002',
  },

  gstNumber: '27AAAAA0000A1Z5',
  panNumber: 'AAAAA0000A',
  tanNumber: 'MUMR12345A',
  registrationNumber: 'REG-2018-MH-001',

  supplierType: SupplierType.WHOLESALER,
  supplierCategory: SupplierCategory.GOLD,

  productsSupplied: ['22K Gold', '24K Gold', 'Gold Coins', 'Gold Bars'],
  specialization: ['Hallmarked Gold', 'Certified Purity'],

  paymentTerms: PaymentTerms.NET30,
  creditPeriod: 30,
  creditLimit: 5000000,

  currentBalance: -250000,
  totalPurchases: 15000000,
  totalPaid: 14750000,
  totalDue: 250000,
  advancePayment: 0,

  rating: 4.5,
  qualityRating: 5,
  deliveryRating: 4,
  priceRating: 5,

  statistics: {
    totalOrders: 145,
    completedOrders: 142,
    pendingOrders: 3,
    cancelledOrders: 0,
    totalPurchased: 15000000,
    averageOrderValue: 103448,
    lastOrderDate: '2024-12-15T10:30:00Z',
    firstOrderDate: '2023-01-10T08:00:00Z',
    averageDeliveryTime: 2,
    onTimeDeliveryPercentage: 98,
  },

  bankDetails: {
    bankName: 'HDFC Bank',
    accountNumber: '50200012345678',
    ifscCode: 'HDFC0001234',
    accountHolderName: 'Rajesh Gold Suppliers Pvt Ltd',
    branchName: 'Kalbadevi Branch',
    accountType: AccountType.CURRENT,
  },

  upiId: 'rajeshgold@hdfc',

  certifications: [
    {
      _id: 'cert_001',
      certificationType: CertificationType.BIS,
      certificateNumber: 'BIS-2023-001',
      issuedBy: 'Bureau of Indian Standards',
      issueDate: '2023-01-15',
      expiryDate: '2026-01-15',
      documentUrl: 'https://example.com/cert_bis.pdf',
    },
  ],

  documents: [
    {
      _id: 'doc_001',
      documentType: DocumentType.GST_CERTIFICATE,
      documentNumber: '27AAAAA0000A1Z5',
      documentUrl: 'https://example.com/gst_cert.pdf',
      uploadedAt: '2023-01-10T08:00:00Z',
    },
  ],

  isActive: true,
  isVerified: true,
  verifiedAt: '2023-01-15T10:00:00Z',
  isPreferred: true,
  isBlacklisted: false,

  notes: 'Excellent quality gold supplier. Very reliable for bulk orders.',
  internalNotes: 'VIP supplier - priority treatment',
  tags: ['gold', 'premium', 'trusted', 'bulk-supplier'],

  createdBy: 'user_123',
  updatedBy: 'user_123',
  createdAt: '2023-01-10T08:00:00Z',
  updatedAt: '2024-12-15T11:00:00Z',
}

// MULTIPLE SUPPLIERS (List data)

export const dummySuppliers: Supplier[] = [
  // 1. Gold Supplier (Preferred)
  {
    _id: '6745a8b3c9d2e1f4a5b6c7d8',
    organizationId: 'org_123456789',
    shopId: 'shop_987654321',
    supplierCode: 'SUP00001',
    businessName: 'Rajesh Gold Suppliers Pvt Ltd',
    displayName: 'Rajesh Gold',
    contactPerson: {
      firstName: 'Rajesh',
      lastName: 'Kumar',
      phone: '9876543210',
      email: 'rajesh@rajeshgold.com',
    },
    address: {
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400002',
    },
    supplierType: SupplierType.WHOLESALER,
    supplierCategory: SupplierCategory.GOLD,
    paymentTerms: PaymentTerms.NET30,
    creditPeriod: 30,
    creditLimit: 5000000,
    currentBalance: -250000,
    totalPurchases: 15000000,
    totalPaid: 14750000,
    totalDue: 250000,
    advancePayment: 0,
    rating: 4.5,
    qualityRating: 5,
    deliveryRating: 4,
    priceRating: 5,
    statistics: {
      totalOrders: 145,
      completedOrders: 142,
      pendingOrders: 3,
      cancelledOrders: 0,
      totalPurchased: 15000000,
      averageOrderValue: 103448,
      averageDeliveryTime: 2,
      onTimeDeliveryPercentage: 98,
    },
    isActive: true,
    isVerified: true,
    isPreferred: true,
    isBlacklisted: false,
    tags: ['gold', 'premium', 'trusted'],
    createdAt: '2023-01-10T08:00:00Z',
    updatedAt: '2024-12-15T11:00:00Z',
  },

  // 2. Diamond Supplier
  {
    _id: '6745a8b3c9d2e1f4a5b6c7d9',
    organizationId: 'org_123456789',
    shopId: 'shop_987654321',
    supplierCode: 'SUP00002',
    businessName: 'Shree Diamond International',
    displayName: 'Shree Diamond',
    contactPerson: {
      firstName: 'Amit',
      lastName: 'Shah',
      phone: '9876543220',
      email: 'amit@shreediamond.com',
      designation: 'Director',
    },
    address: {
      city: 'Surat',
      state: 'Gujarat',
      pincode: '395003',
    },
    gstNumber: '24BBBBB1111B1Z6',
    supplierType: SupplierType.MANUFACTURER,
    supplierCategory: SupplierCategory.DIAMOND,
    paymentTerms: PaymentTerms.NET45,
    creditPeriod: 45,
    creditLimit: 8000000,
    currentBalance: 0,
    totalPurchases: 12500000,
    totalPaid: 12500000,
    totalDue: 0,
    advancePayment: 100000,
    rating: 4.7,
    qualityRating: 5,
    deliveryRating: 5,
    priceRating: 4,
    statistics: {
      totalOrders: 89,
      completedOrders: 87,
      pendingOrders: 2,
      cancelledOrders: 0,
      totalPurchased: 12500000,
      averageOrderValue: 140449,
      averageDeliveryTime: 5,
      onTimeDeliveryPercentage: 95,
    },
    isActive: true,
    isVerified: true,
    isPreferred: true,
    isBlacklisted: false,
    tags: ['diamond', 'certified', 'surat'],
    createdAt: '2023-02-15T09:00:00Z',
    updatedAt: '2024-12-14T10:00:00Z',
  },

  // 3. Silver Supplier
  {
    _id: '6745a8b3c9d2e1f4a5b6c7e0',
    organizationId: 'org_123456789',
    shopId: 'shop_987654321',
    supplierCode: 'SUP00003',
    businessName: 'Prakash Silver Works',
    displayName: 'Prakash Silver',
    contactPerson: {
      firstName: 'Prakash',
      lastName: 'Mehta',
      phone: '9876543230',
      email: 'prakash@prakashsilver.com',
    },
    address: {
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302001',
    },
    supplierType: SupplierType.WHOLESALER,
    supplierCategory: SupplierCategory.SILVER,
    paymentTerms: PaymentTerms.NET30,
    creditPeriod: 30,
    creditLimit: 2000000,
    currentBalance: -50000,
    totalPurchases: 3500000,
    totalPaid: 3450000,
    totalDue: 50000,
    advancePayment: 0,
    rating: 4.2,
    qualityRating: 4,
    deliveryRating: 4,
    priceRating: 5,
    statistics: {
      totalOrders: 67,
      completedOrders: 65,
      pendingOrders: 2,
      cancelledOrders: 0,
      totalPurchased: 3500000,
      averageOrderValue: 52239,
      averageDeliveryTime: 3,
      onTimeDeliveryPercentage: 92,
    },
    isActive: true,
    isVerified: true,
    isPreferred: false,
    isBlacklisted: false,
    tags: ['silver', 'traditional'],
    createdAt: '2023-03-20T10:00:00Z',
    updatedAt: '2024-12-13T09:00:00Z',
  },

  // 4. Gemstone Supplier
  {
    _id: '6745a8b3c9d2e1f4a5b6c7e1',
    organizationId: 'org_123456789',
    shopId: 'shop_987654321',
    supplierCode: 'SUP00004',
    businessName: 'Royal Gems & Stones',
    displayName: 'Royal Gems',
    contactPerson: {
      firstName: 'Suresh',
      lastName: 'Patel',
      phone: '9876543240',
      email: 'suresh@royalgems.com',
      designation: 'Owner',
    },
    address: {
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302002',
    },
    supplierType: SupplierType.DISTRIBUTOR,
    supplierCategory: SupplierCategory.GEMSTONE,
    paymentTerms: PaymentTerms.NET15,
    creditPeriod: 15,
    creditLimit: 1500000,
    currentBalance: -75000,
    totalPurchases: 2800000,
    totalPaid: 2725000,
    totalDue: 75000,
    advancePayment: 0,
    rating: 4.0,
    qualityRating: 4,
    deliveryRating: 4,
    priceRating: 4,
    statistics: {
      totalOrders: 54,
      completedOrders: 52,
      pendingOrders: 2,
      cancelledOrders: 0,
      totalPurchased: 2800000,
      averageOrderValue: 51852,
      averageDeliveryTime: 4,
      onTimeDeliveryPercentage: 88,
    },
    isActive: true,
    isVerified: true,
    isPreferred: false,
    isBlacklisted: false,
    tags: ['gemstone', 'colored-stones'],
    createdAt: '2023-04-10T11:00:00Z',
    updatedAt: '2024-12-12T08:00:00Z',
  },

  // 5. Making/Labor Supplier
  {
    _id: '6745a8b3c9d2e1f4a5b6c7e2',
    organizationId: 'org_123456789',
    shopId: 'shop_987654321',
    supplierCode: 'SUP00005',
    businessName: 'Karigari Jewellery Making',
    displayName: 'Karigari Making',
    contactPerson: {
      firstName: 'Ramesh',
      lastName: 'Soni',
      phone: '9876543250',
      email: 'ramesh@karigari.com',
    },
    address: {
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400003',
    },
    supplierType: SupplierType.ARTISAN,
    supplierCategory: SupplierCategory.MAKING,
    paymentTerms: PaymentTerms.COD,
    creditPeriod: 0,
    creditLimit: 500000,
    currentBalance: 0,
    totalPurchases: 1200000,
    totalPaid: 1200000,
    totalDue: 0,
    advancePayment: 25000,
    rating: 4.8,
    qualityRating: 5,
    deliveryRating: 5,
    priceRating: 4,
    statistics: {
      totalOrders: 98,
      completedOrders: 98,
      pendingOrders: 0,
      cancelledOrders: 0,
      totalPurchased: 1200000,
      averageOrderValue: 12245,
      averageDeliveryTime: 7,
      onTimeDeliveryPercentage: 100,
    },
    isActive: true,
    isVerified: true,
    isPreferred: true,
    isBlacklisted: false,
    tags: ['making', 'handcrafted', 'skilled'],
    createdAt: '2023-05-01T12:00:00Z',
    updatedAt: '2024-12-11T07:00:00Z',
  },

  // 6. Packaging Supplier
  {
    _id: '6745a8b3c9d2e1f4a5b6c7e3',
    organizationId: 'org_123456789',
    shopId: 'shop_987654321',
    supplierCode: 'SUP00006',
    businessName: 'Premium Packaging Solutions',
    displayName: 'Premium Pack',
    contactPerson: {
      firstName: 'Vikram',
      lastName: 'Gupta',
      phone: '9876543260',
      email: 'vikram@premiumpack.com',
    },
    address: {
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110001',
    },
    supplierType: SupplierType.MANUFACTURER,
    supplierCategory: SupplierCategory.PACKAGING,
    paymentTerms: PaymentTerms.NET30,
    creditPeriod: 30,
    creditLimit: 300000,
    currentBalance: -15000,
    totalPurchases: 450000,
    totalPaid: 435000,
    totalDue: 15000,
    advancePayment: 0,
    rating: 4.3,
    qualityRating: 4,
    deliveryRating: 5,
    priceRating: 4,
    statistics: {
      totalOrders: 45,
      completedOrders: 43,
      pendingOrders: 2,
      cancelledOrders: 0,
      totalPurchased: 450000,
      averageOrderValue: 10000,
      averageDeliveryTime: 2,
      onTimeDeliveryPercentage: 96,
    },
    isActive: true,
    isVerified: true,
    isPreferred: false,
    isBlacklisted: false,
    tags: ['packaging', 'boxes', 'premium'],
    createdAt: '2023-06-15T13:00:00Z',
    updatedAt: '2024-12-10T06:00:00Z',
  },

  // 7. Platinum Supplier (Inactive)
  {
    _id: '6745a8b3c9d2e1f4a5b6c7e4',
    organizationId: 'org_123456789',
    shopId: 'shop_987654321',
    supplierCode: 'SUP00007',
    businessName: 'Platinum World Suppliers',
    displayName: 'Platinum World',
    contactPerson: {
      firstName: 'Karan',
      lastName: 'Verma',
      phone: '9876543270',
      email: 'karan@platinumworld.com',
    },
    address: {
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560001',
    },
    supplierType: SupplierType.IMPORTER,
    supplierCategory: SupplierCategory.PLATINUM,
    paymentTerms: PaymentTerms.NET60,
    creditPeriod: 60,
    creditLimit: 3000000,
    currentBalance: 0,
    totalPurchases: 850000,
    totalPaid: 850000,
    totalDue: 0,
    advancePayment: 0,
    rating: 3.8,
    qualityRating: 4,
    deliveryRating: 3,
    priceRating: 4,
    statistics: {
      totalOrders: 12,
      completedOrders: 12,
      pendingOrders: 0,
      cancelledOrders: 0,
      totalPurchased: 850000,
      averageOrderValue: 70833,
      averageDeliveryTime: 10,
      onTimeDeliveryPercentage: 75,
    },
    isActive: false,
    isVerified: true,
    isPreferred: false,
    isBlacklisted: false,
    tags: ['platinum', 'imported'],
    createdAt: '2023-07-20T14:00:00Z',
    updatedAt: '2024-11-01T05:00:00Z',
  },

  // 8. Pearl Supplier (Blacklisted)
  {
    _id: '6745a8b3c9d2e1f4a5b6c7e5',
    organizationId: 'org_123456789',
    shopId: 'shop_987654321',
    supplierCode: 'SUP00008',
    businessName: 'Ocean Pearl Traders',
    displayName: 'Ocean Pearl',
    contactPerson: {
      firstName: 'Deepak',
      lastName: 'Jain',
      phone: '9876543280',
      email: 'deepak@oceanpearl.com',
    },
    address: {
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500001',
    },
    supplierType: SupplierType.DISTRIBUTOR,
    supplierCategory: SupplierCategory.PEARLS,
    paymentTerms: PaymentTerms.NET30,
    creditPeriod: 30,
    creditLimit: 1000000,
    currentBalance: -150000,
    totalPurchases: 650000,
    totalPaid: 500000,
    totalDue: 150000,
    advancePayment: 0,
    rating: 2.5,
    qualityRating: 2,
    deliveryRating: 3,
    priceRating: 3,
    statistics: {
      totalOrders: 18,
      completedOrders: 15,
      pendingOrders: 0,
      cancelledOrders: 3,
      totalPurchased: 650000,
      averageOrderValue: 36111,
      averageDeliveryTime: 15,
      onTimeDeliveryPercentage: 60,
    },
    isActive: false,
    isVerified: true,
    isPreferred: false,
    isBlacklisted: true,
    blacklistReason:
      'Poor quality products and delayed deliveries. Multiple customer complaints.',
    blacklistedAt: '2024-10-15T10:00:00Z',
    tags: ['pearls', 'blacklisted'],
    createdAt: '2023-08-10T15:00:00Z',
    updatedAt: '2024-10-15T10:00:00Z',
  },

  // 9. Mixed Category Supplier
  {
    _id: '6745a8b3c9d2e1f4a5b6c7e6',
    organizationId: 'org_123456789',
    shopId: 'shop_987654321',
    supplierCode: 'SUP00009',
    businessName: 'Universal Jewellers Supply',
    displayName: 'Universal Supply',
    contactPerson: {
      firstName: 'Anil',
      lastName: 'Sharma',
      phone: '9876543290',
      email: 'anil@universalsupply.com',
    },
    address: {
      city: 'Kolkata',
      state: 'West Bengal',
      pincode: '700001',
    },
    supplierType: SupplierType.WHOLESALER,
    supplierCategory: SupplierCategory.MIXED,
    paymentTerms: PaymentTerms.NET30,
    creditPeriod: 30,
    creditLimit: 2500000,
    currentBalance: -100000,
    totalPurchases: 4200000,
    totalPaid: 4100000,
    totalDue: 100000,
    advancePayment: 0,
    rating: 4.1,
    qualityRating: 4,
    deliveryRating: 4,
    priceRating: 4,
    statistics: {
      totalOrders: 78,
      completedOrders: 76,
      pendingOrders: 2,
      cancelledOrders: 0,
      totalPurchased: 4200000,
      averageOrderValue: 53846,
      averageDeliveryTime: 4,
      onTimeDeliveryPercentage: 90,
    },
    isActive: true,
    isVerified: true,
    isPreferred: false,
    isBlacklisted: false,
    tags: ['mixed', 'variety'],
    createdAt: '2023-09-05T16:00:00Z',
    updatedAt: '2024-12-09T04:00:00Z',
  },

  // 10. New Supplier (Recently Added)
  {
    _id: '6745a8b3c9d2e1f4a5b6c7e7',
    organizationId: 'org_123456789',
    shopId: 'shop_987654321',
    supplierCode: 'SUP00010',
    businessName: 'New Age Diamonds',
    displayName: 'New Age',
    contactPerson: {
      firstName: 'Rohit',
      lastName: 'Agarwal',
      phone: '9876543300',
      email: 'rohit@newagediamonds.com',
    },
    address: {
      city: 'Surat',
      state: 'Gujarat',
      pincode: '395004',
    },
    supplierType: SupplierType.MANUFACTURER,
    supplierCategory: SupplierCategory.DIAMOND,
    paymentTerms: PaymentTerms.IMMEDIATE,
    creditPeriod: 0,
    creditLimit: 500000,
    currentBalance: 0,
    totalPurchases: 150000,
    totalPaid: 150000,
    totalDue: 0,
    advancePayment: 0,
    statistics: {
      totalOrders: 3,
      completedOrders: 3,
      pendingOrders: 0,
      cancelledOrders: 0,
      totalPurchased: 150000,
      averageOrderValue: 50000,
      averageDeliveryTime: 3,
      onTimeDeliveryPercentage: 100,
    },
    isActive: true,
    isVerified: false,
    isPreferred: false,
    isBlacklisted: false,
    tags: ['diamond', 'new'],
    createdAt: '2024-11-20T17:00:00Z',
    updatedAt: '2024-12-08T03:00:00Z',
  },
]

// SUPPLIER STATISTICS

export const dummySupplierStats = {
  totalSuppliers: 10,
  activeSuppliers: 8,
  preferredSuppliers: 3,
  blacklistedSuppliers: 1,
  totalPurchases: 40300000,
  totalDue: 640000,
  totalAdvance: 125000,
}

// TOP SUPPLIERS

export const dummyTopSuppliers: Supplier[] = [
  dummySuppliers[0], // Rajesh Gold - 15M
  dummySuppliers[1], // Shree Diamond - 12.5M
  dummySuppliers[8], // Universal Supply - 4.2M
  dummySuppliers[2], // Prakash Silver - 3.5M
  dummySuppliers[3], // Royal Gems - 2.8M
]

// FILTER OPTIONS (for dropdowns)

export const supplierTypeOptions = [
  { value: SupplierType.MANUFACTURER, label: 'Manufacturer' },
  { value: SupplierType.WHOLESALER, label: 'Wholesaler' },
  { value: SupplierType.DISTRIBUTOR, label: 'Distributor' },
  { value: SupplierType.ARTISAN, label: 'Artisan' },
  { value: SupplierType.IMPORTER, label: 'Importer' },
  { value: SupplierType.OTHER, label: 'Other' },
]

export const supplierCategoryOptions = [
  { value: SupplierCategory.GOLD, label: 'Gold' },
  { value: SupplierCategory.SILVER, label: 'Silver' },
  { value: SupplierCategory.DIAMOND, label: 'Diamond' },
  { value: SupplierCategory.PLATINUM, label: 'Platinum' },
  { value: SupplierCategory.GEMSTONE, label: 'Gemstone' },
  { value: SupplierCategory.PEARLS, label: 'Pearls' },
  { value: SupplierCategory.MAKING, label: 'Making/Labor' },
  { value: SupplierCategory.PACKAGING, label: 'Packaging' },
  { value: SupplierCategory.MIXED, label: 'Mixed' },
]

export const paymentTermsOptions = [
  { value: PaymentTerms.IMMEDIATE, label: 'Immediate' },
  { value: PaymentTerms.COD, label: 'Cash on Delivery' },
  { value: PaymentTerms.NET15, label: 'Net 15 Days' },
  { value: PaymentTerms.NET30, label: 'Net 30 Days' },
  { value: PaymentTerms.NET45, label: 'Net 45 Days' },
  { value: PaymentTerms.NET60, label: 'Net 60 Days' },
  { value: PaymentTerms.CUSTOM, label: 'Custom Terms' },
]

// EMPTY SUPPLIER TEMPLATE (for forms)

export const emptySupplier: Partial<Supplier> = {
  businessName: '',
  displayName: '',
  contactPerson: {
    firstName: '',
    lastName: '',
    phone: '',
    email: '',
  },
  address: {
    street: '',
    city: '',
    state: '',
    country: 'India',
    pincode: '',
  },
  supplierType: SupplierType.WHOLESALER,
  supplierCategory: SupplierCategory.MIXED,
  paymentTerms: PaymentTerms.NET30,
  creditPeriod: 30,
  creditLimit: 0,
  isActive: true,
  isVerified: false,
  isPreferred: false,
  tags: [],
}

export default {
  dummySupplier,
  dummySuppliers,
  dummySupplierStats,
  dummyTopSuppliers,
  supplierTypeOptions,
  supplierCategoryOptions,
  paymentTermsOptions,
  emptySupplier,
}
